.TH Tilux 1 GNU
.SH NAME
tilux

.SH SYNOPSIS
.B ./tilux
[-h]
[--help]

.SH DESCRIPTTION
.B tilux
is a CLI that has many useful and consice scripts. The scripts are located in cryptography, monitoring, networking and system folder and you then specify which script you want to run.
.PP
Shortly about the folders:
.PP
Cryptography consists of ccrypt, openssl, pyca and zip and all have an encryption and decryption option.
.PP
Monitoring consists of CPU, memory and website.
.PP
Networking consists of IP and server pinging.
.PP
System consists of many system related scripts such as. configurations, system info etc.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
display help information.
.TP

.SH AUTHOR
Endormi
