# TODO
AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Rubocop also checks pre-commit pkg (only if you use venv).
# You might need to do rubocop -a few times.
Gemspec/RequiredRubyVersion:
  Enabled: false

# Ignored at least for now
Lint/ShadowedArgument:
  Enabled: false
