Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

# Rubocop also checks pre-commit pkg (only if you use venv).
# You might need to do rubocop -a few times.
Gemspec/RequiredRubyVersion:
  Enabled: false

Style/IdenticalConditionalBranches:
  # I will look into this later
  Enabled: false
