# TODO

# Some of these will be removed later.
# I will be refactoring the code ASAP
AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/MultilineWhenThen:
  Enabled: false

Style/Semicolon:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

# Rubocop also checks pre-commit pkg (only if you use venv).
# You might need to do rubocop -a few times.
Gemspec/RequiredRubyVersion:
  Enabled: false
