#!/bin/bash

echo -e "\n\nThis might take a while...\n\n"

# Quick hack to not run the code
# when using Docker so it doesn't get
# stuck on read prompt
if [[ $1 != "-y" ]]; then
  echo "This build will install multiple packages."
  echo -e "You probably already have a lot of the packages, if you have done anything with your OS.\n"
  echo -e "Will install python3, pip3, ruby, lsb-core, build-essentials & graphicsmagick.\n"

  read -p "Do you want to continue? (Y/n) " continue
  continue="$(echo ${continue} | tr 'A-Z' 'a-z')"

  if [ "$continue" != "y" ] && [ "$continue" != "yes" ]; then
    echo "Exiting build.."
    exit
  fi
fi

g="\033[0;32m"
w="\033[1;37m"

bash chmodx

# Python3 is required to run the python scripts
if [[ "$(which python3)" == "" ]]; then
  sudo apt update
  sudo apt install -y python3
fi

if [[ "$(which pip3)" == "" ]]; then
  sudo apt update
  sudo apt install -y python3-pip
fi

# Ruby is required to run ruby scripts
if [[ "$(which ruby)" == "" ]]; then
  sudo apt update
  sudo apt install -y ruby-full

  export GEM_HOME="$HOME/.gem"

  gem install bundler -v 2.1.4
fi

# lsb_release is required to run sys/distro.sh script
if [[ "$(which lsb_release)" == "" ]]; then
  sudo apt update
  sudo apt install -y lsb-core
fi

# Required for compiling C/C++ files
if [[ "$(which gcc)" == "" ]]; then
  sudo apt update
  sudo apt install -y build-essential
fi

if [[ "$(which gm)" == "" ]]; then
  sudo apt update
  sudo apt install -y graphicsmagick
fi

# TODO: Run venv after build
if [[ $1 == "venv" ]]; then
  if [[ "$(which virtualenv)" == "" ]]; then
    # virtualenv probably tries to install here
    export PATH=$HOME/.local/bin/:$PATH
    pip3 install virtualenv
  fi
  if [[ ! -d "venv" ]]; then
    # To fix the warning where python pkgs
    # are installed in ./local/bin
    # after virtualenv path.
    # TODO
    export PATH=/usr/local/bin/:$PATH
    virtualenv venv
  fi
  activate() {
    . ./venv/bin/activate
  }
  activate
fi

# fixes issue with cryptography package
python3 -m pip install -U pip

# Compile C files
make -s

pip3 install -r requirements.txt && bundle install

clear

echo "Note: Certain scripts might require you to install a package. it's included in the script."
echo -e "${g}Thanks for using Tilux!${w}\n"
