#!/bin/bash

echo -e "\n\nThis might take a while...\n\n"

# Quick hack to not run the code
# when using Docker so it doesn't get
# stuck on read prompt
if [[ $1 != "-y" ]]; then
  echo "This build will install multiple packages."
  echo -e "You probably already have a lot of the packages, if you have done anything with your OS.\n"
  echo -e "Will install python3, pip3, ruby, lsb-core, build-essentials & graphicsmagick.\n"

  read -p "Do you want to continue? (Y/n) " continue
  continue="$(echo ${continue} | tr 'A-Z' 'a-z')"

  if [ "$continue" != "y" ] && [ "$continue" != "yes" ]; then
    echo "Exiting build.."
    exit
  fi
fi

g="\033[0;32m"
w="\033[1;37m"

bash chmodx
bash pkgs

# TODO: Run venv after build
if [[ $1 == "venv" ]]; then
  if [[ "$(which virtualenv)" == "" ]]; then
    # virtualenv probably tries to install here
    export PATH=$HOME/.local/bin/:$PATH
    pip3 install virtualenv
  fi
  if [[ ! -d "venv" ]]; then
    # To fix the warning where python pkgs
    # are installed in ./local/bin
    # after virtualenv path.
    # TODO
    export PATH=/usr/local/bin/:$PATH
    virtualenv venv
  fi
  activate() {
    . ./venv/bin/activate
  }
  activate
fi

# fixes issue with cryptography package
python3 -m pip install -U pip

# Compile C files
make -s

pip3 install -r requirements.txt && bundle install

clear

echo "Note: Certain scripts might require you to install a package. It's included in the script."
echo -e "${g}Thanks for using Tilux!${w}\n"
