#!/bin/bash

g="\033[0;32m"
w="\033[1;37m"

bash chmodx

# Python3 is required to run the python scripts
if [[ "$(which python3)" == "" ]]; then
  sudo apt-get upgrade
  sudo apt install python3
fi

if [[ "$(which pip3)" == "" ]]; then
  sudo apt-get upgrade
  sudo apt install python3-pip
fi

# Ruby is required to run ruby scripts
if [[ "$(which ruby)" == "" ]]; then
  sudo apt-get upgrade
  sudo apt install ruby-dev ruby-bundler ruby-rspec-core make
fi

# lsb_release is required to run sys/distro.sh script
if [[ "$(which lsb_release)" == "" ]]; then
  sudo apt-get upgrade
  sudo apt install lsb-core
fi

# Required for compiling C/C++ files
if [ "$(which gcc)" == "" ] || [ "$(which g++)" == "" ]; then
  sudo apt-get upgrade
  sudo apt install build-essential
fi

if [[ "$(which gm)" == "" ]]; then
  sudo apt-get upgrade
  sudo apt install graphicsmagick
fi

# TODO: Run venv after build
if [[ $1 == "venv" ]]; then
  if [[ "$(which virtualenv)" == "" ]]; then
    # virtualenv probably tries to install here
    export PATH=$HOME/.local/bin/:$PATH
    pip3 install virtualenv
  fi
  if [[ ! -d "venv" ]]; then
    # To fix the warning where python pkgs
    # are installed in ./local/bin
    # after virtualenv path.
    # TODO
    export PATH=$HOME/usr/bin/python3:$PATH
    virtualenv venv
  fi
  activate() {
    . ./venv/bin/activate
  }
  activate
fi

# fixes issue with cryptography package
python3 -m pip install -U pip

# Compile C files
make -s

pip3 install -r requirements.txt && bundle install

clear

echo -e "${g}Thanks for using Tilux!${w}\n"
