#!/bin/bash

# Bash scripts
chmod +x ./cryptography/ccrypt/ccrypt_encryption.sh
chmod +x ./cryptography/ccrypt/ccrypt_decryption.sh

#chmod +x ./cryptography/gpg/gpg_encryption.sh
#chmod +x ./cryptography/gpg/gpg_decryption.sh

chmod +x ./cryptography/openssl/openssl_encryption.sh
chmod +x ./cryptography/openssl/openssl_decryption.sh

chmod +x ./cryptography/zip/zip_encryption.sh
chmod +x ./cryptography/zip/zip_decryption.sh

chmod +x ./monitoring/cpu_monitoring.sh
chmod +x ./monitoring/mem_monitoring.sh

chmod +x ./sys/config/git_config.sh
chmod +x ./sys/config/gnome_term_profile_dump.sh
chmod +x ./sys/config/gnome_term_profile_load.sh

chmod +x ./sys/file_folder/bf.sh
chmod +x ./sys/file_folder/last_updated.sh

chmod +x ./sys/info/bit.sh
chmod +x ./sys/info/distro.sh
chmod +x ./sys/info/kernel_version.sh
chmod +x ./sys/info/prv.sh

chmod +x ./sys/other/add_alias.sh
chmod +x ./sys/other/clean.sh
chmod +x ./sys/other/remove_line.sh
chmod +x ./sys/other/resize_terminal.sh

chmod +x ./sys/proc/cpu_name.sh
chmod +x ./sys/proc/gpu_name.sh

chmod +x ./sys/shutdown/force_poweroff.sh
chmod +x ./sys/shutdown/force_reboot.sh

chmod +x ./scripts/add_alias
chmod +x ./scripts/add_alias_venv
chmod +x ./scripts/cformat
chmod +x ./scripts/install_req
chmod +x ./scripts/pre_commit
chmod +x ./scripts/resize_term
chmod +x ./scripts/run_check
chmod +x ./scripts/start_dcompose

# Python scripts
chmod +x ./cryptography/pyca/encrypt.py
chmod +x ./cryptography/pyca/decrypt.py

chmod +x ./monitoring/website_monitoring.py

chmod +x ./networking/ip_pinging.py
chmod +x ./networking/server_pinging.py

# Ruby scripts
chmod +x tilux

chmod +x ./sys/file_folder/del.rb
chmod +x ./sys/file_folder/exists.rb
chmod +x ./sys/file_folder/fd.rb
chmod +x ./sys/file_folder/file_updated.rb

chmod +x ./sys/img/convert_img.rb
chmod +x ./sys/img/img_info.rb
chmod +x ./sys/img/resize_img.rb
chmod +x ./sys/img/rotate_img.rb

chmod +x ./sys/info/ip.rb
chmod +x ./sys/info/os.rb
chmod +x ./sys/info/root.rb

chmod +x ./sys/other/convert_doc_to_pdf.rb
chmod +x ./sys/other/parse_date.rb

# Generate keys
#chmod +x ./cryptography/gpg/gpg_generate_and_verify_keys.sh
chmod +x ./cryptography/pyca/generate_key.py
