#!/bin/bash

chmod +x ./cryptography/ccrypt/ccrypt_encryption.sh
chmod +x ./cryptography/ccrypt/ccrypt_decryption.sh
chmod +x ./cryptography/gpg/gpg_encryption.sh
chmod +x ./cryptography/gpg/gpg_decryption.sh
chmod +x ./cryptography/openssl/openssl_encryption.sh
chmod +x ./cryptography/openssl/openssl_decryption.sh
chmod +x ./cryptography/zip/zip_encryption.sh
chmod +x ./cryptography/zip/zip_decryption.sh
chmod +x ./monitoring/cpu_monitoring.sh
chmod +x ./monitoring/mem_monitoring.sh
chmod +x ./sys/add_alias.sh
chmod +x ./sys/bf.sh
chmod +x ./sys/bit.sh
chmod +x ./sys/clean.sh
chmod +x ./sys/cpu_name.sh
chmod +x ./sys/distro.sh
chmod +x ./sys/force_poweroff.sh
chmod +x ./sys/force_reboot.sh
chmod +x ./sys/git_config.sh
chmod +x ./sys/gnome_term_profile_dump.sh
chmod +x ./sys/gnome_term_profile_load.sh
chmod +x ./sys/gpu_name.sh
chmod +x ./sys/kernel_version.sh
chmod +x ./sys/last_updated.sh
chmod +x ./sys/prv.sh
chmod +x ./sys/resize_terminal.sh

chmod +x ./scripts/add_alias
chmod +x ./scripts/cformat
chmod +x ./scripts/install_req
chmod +x ./scripts/resize_term
chmod +x ./scripts/start_dcompose

chmod +x ./cryptography/pyca/encrypt.py
chmod +x ./cryptography/pyca/decrypt.py
chmod +x ./monitoring/website_monitoring.py
chmod +x ./networking/ip_pinging.py
chmod +x ./networking/server_pinging.py

chmod +x tilux
chmod +x ./sys/convert_doc_to_pdf.rb
chmod +x ./sys/convert_img.rb
chmod +x ./sys/del.rb
chmod +x ./sys/exists.rb
chmod +x ./sys/fd.rb
chmod +x ./sys/file_updated.rb
chmod +x ./sys/hostname.rb
chmod +x ./sys/img_info.rb
chmod +x ./sys/ip.rb
chmod +x ./sys/os.rb
chmod +x ./sys/parse_date.rb
chmod +x ./sys/resize_img.rb
chmod +x ./sys/root.rb
chmod +x ./sys/rotate_img.rb

# Generate keys
chmod +x ./cryptography/gpg/gpg_generate_and_verify_keys.sh
chmod +x ./cryptography/pyca/generate_key.py

chmod +x ./proc_script.rb
