#!/bin/bash

check_and_install_package() {
  package=$1

  if ! command -v "$package" &>/dev/null; then
    echo "Installing $package which is required to run this script."
    sudo apt update
    sudo apt install $package
    clear
  fi
}

check_and_install_package jq
check_and_install_package fzf
check_and_install_package unzip

releases=$(curl -sL https://api.github.com/repos/endormi/tilux/releases | jq -r ".[]" | jq -r ".tag_name")
version=$(echo $releases | tr ' ' '\n' | fzf)

file_ext="zip"
wget https://github.com/endormi/tilux/archive/refs/tags/$version.$file_ext && unzip $version.$file_ext && rm $version.$file_ext
