#!/bin/bash

# Python3 is required to run the python scripts
if ! command -v python3 &>/dev/null; then
  sudo apt update
  sudo apt install -y python3
fi

if ! command -v pip3 &>/dev/null; then
  sudo apt update
  sudo apt install -y python3-pip
fi

# Ruby is required to run ruby scripts
if ! command -v ruby &>/dev/null; then
  sudo apt update
  sudo apt install -y ruby-full

  export GEM_HOME="$HOME/.gem"

  gem install bundler # -v 2.1.4
fi

# lsb_release is required to run sys/kernel_version.sh script
if ! command -v lsb_release &>/dev/null; then
  sudo apt update
  sudo apt install -y lsb-core
fi

# Required for compiling C/C++ files
if ! command -v gcc &>/dev/null; then
  sudo apt update
  sudo apt install -y build-essential
fi

if ! command -v gm &>/dev/null; then
  sudo apt update
  sudo apt install -y graphicsmagick
fi

# xdg-open is included inside xdg-utils
if ! command -v xdg-open &>/dev/null; then
  sudo apt update
  sudo apt install -y xdg-utils
fi
