#!/bin/bash

# Python3 is required to run the python scripts
if [[ -z "$(which python3)" ]]; then
  sudo apt update
  sudo apt install -y python3
fi

if [[ -z "$(which pip3)" ]]; then
  sudo apt update
  sudo apt install -y python3-pip
fi

# Ruby is required to run ruby scripts
if [[ -z "$(which ruby)" ]]; then
  sudo apt update
  sudo apt install -y ruby-full

  export GEM_HOME="$HOME/.gem"

  gem install bundler # -v 2.1.4
fi

# lsb_release is required to run sys/kernel_version.sh script
if [[ -z "$(which lsb_release)" ]]; then
  sudo apt update
  sudo apt install -y lsb-core
fi

# Required for compiling C/C++ files
if [[ -z "$(which gcc)" ]]; then
  sudo apt update
  sudo apt install -y build-essential
fi

if [[ -z "$(which gm)" ]]; then
  sudo apt update
  sudo apt install -y graphicsmagick
fi

# xdg-open is included inside xdg-utils
if [[ -z "$(which xdg-open)" ]]; then
  sudo apt update
  sudo apt install -y xdg-utils
fi
