#!/usr/bin/ruby

require_relative "tools/col"
require_relative "tools/def"
require_relative "tools/catch_exception"


version="v.0.2.5"
puts "
ooooooooooooo ooooo ooooo        ooooo     ooo ooooooo  ooooo
8    888    8  888   888          888       8    8888    d8
     888       888   888          888       8     Y888..8P
     888       888   888          888       8       8888
     888       888   888          888       8     .8PY888.
     888       888   888       o   88.    .8     d8    888b
    o888o     o888o o888ooooood8     YbodP     o888o  o88888o
".green
print "version".white
print " #{version}".light_yellow
print " by Endormi ".white
link="\e]8;;https://github.com/endormi/tilux\a(github.com/endormi/tilux)\e]8;;\a"
puts link.white

sleep 1

prompt="tilux~# ".green


def sys(file)
  system("clear")
  system(file)
end

def func_to_run(title, func)
  system("clear")
  echo(title)
  system(func)
end

def echo(text)
  puts text.white
end


if (ARGV.empty?)
  puts "\nWhat script do you want to run?\n".white
  echo("::Info::")
  system("bash tools/funcs info")
  echo("::Cryptography::")
  system("bash tools/funcs cryptography")
  echo("::Monitoring::")
  system("bash tools/funcs monitoring")
  echo("::Networking::")
  system("bash tools/funcs networking")
  echo("::System::")
  system("bash tools/funcs sys")
  #echo("misc")
  #system("bash tools/funcs misc")
  echo("::--help::")
  system("bash tools/funcs help2")

  list_of_commands="Info, Cryptography, Monitoring, Networking, Sys && --help"

  puts "Choices: #{list_of_commands}"
  print "#{prompt} "
  c = gets.chomp.to_s.downcase.strip

  case c
    when "info"
      sys("./info.rb")

    when "cryptography", "crypto"
      func_to_run("::Cryptography::", "bash tools/funcs cryptography")
      print "#{prompt} "
      input = gets.chomp.to_s.downcase.strip

      case input
        when "1", "-c", "--c", "-C", "--C"
          system("clear")
          echo("::CCRYPT::")
          cryptography_encryption()
          print "#{prompt} "
          i = gets.chomp.to_s.downcase.strip

          ccrypt_options(i)

        when "2", "-g", "--g", "-G", "--G"
          system("clear")
          echo("::GPG::")
          cryptography_encryption()
          print "#{prompt} "
          i = gets.chomp.to_s.downcase.strip

          gpg_options(i)

        when "3", "-o", "--o", "-O", "--O"
          system("clear")
          echo("::Openssl::")
          cryptography_encryption()
          print "#{prompt} "
          i = gets.chomp.to_s.downcase.strip

          openssl_options(i)

        when "4", "-p", "--p", "-P", "--P"
          system("clear")
          echo("::Pyca::")
          cryptography_encryption()
          print "#{prompt} "
          i = gets.chomp.to_s.downcase.strip

          pyca_options(i)

        when "5", "-z", "--z", "-Z", "--Z"
          system("clear")
          echo("::Zip::")
          cryptography_encryption()
          print "#{prompt} "
          i = gets.chomp.to_s.downcase.strip

          zip_options(i)

        else
          # TODO
          puts "Invalid choice"
        end

    when "monitoring"
      func_to_run("::Monitoring::", "bash tools/funcs monitoring")
      print "#{prompt} "
      input = gets.chomp.to_s.downcase.strip

      monitoring_options(input)

    when "networking", "net"
      func_to_run("::Networking::", "bash tools/funcs networking")
      print "#{prompt} "
      input = gets.chomp.to_s.downcase.strip

      networking_options(input)

    when "sys", "system"
      func_to_run("::System::", "bash tools/funcs sys")
      print "#{prompt} "
      input = gets.chomp.to_s.downcase.strip

      sys_options(input)

    #when "misc"
    #  puts "misc"

    when "help", "--help", "--h"
      func_to_run("::--help::", "bash tools/funcs help")
    else
      puts("\nNot a valid choice!")
      puts "Use #{list_of_commands}"
  end

else
  case ARGV[0]
    when "info"
        sys("./info.rb")

    when "cryptography", "crypto"
      case ARGV[1]
        when "1", "-c", "--c", "-C", "--C"
          ccrypt_options(ARGV[2])

        when "2", "-g", "--g", "-G", "--G"
          gpg_options(ARGV[2])

        when "3", "-o", "--o", "-O", "--O"
          openssl_options(ARGV[2])

        when "4", "-p", "--p", "-P", "--P"
          pyca_options(ARGV[2])

        when "5", "-z", "--z", "-Z", "--Z"
          zip_options(ARGV[2])
        else
          # TODO
          puts "Invalid choice"
      end

    when "monitoring"
      monitoring_options(ARGV[1])

    when "networking", "net"
      networking_options(ARGV[1])

    when "sys", "system"
      sys_options(ARGV[1])

    #when "misc"
    #  puts("misc")

    when "help", "--help", "--h"
      func_to_run("--h", "bash tools/funcs help")
    else
      puts("Not a valid choice!")
  end
end
