#!/bin/bash

source ansi-colors

sudo chmod +x tilux
sudo chmod +x ./info/host.sh
sudo chmod +x ./info/ip_addr.sh
sudo chmod +x ./misc/exists.sh
sudo chmod +x ./monitoring/cpu_monitoring.sh
sudo chmod +x ./monitoring/mem_monitoring.sh

clear

echo -e "${g}Thanks for using Tilux!${w}"
echo

read -p "Do you want to run the script right now? (Y/n): " input
input="$(echo ${input} | tr 'A-Z' 'a-z')"
if [[ $input == "y" ]]; then
  clear
  ./tilux
else
  echo Exiting...
  sleep 1
  clear
  exit
fi
