#!/bin/bash

source ansi-colors

chmod +x tilux
chmod +x ./cryptography/ccrypt/ccrypt_encryption.sh
chmod +x ./cryptography/ccrypt/ccrypt_decryption.sh
chmod +x ./cryptography/gpg/gpg_encryption.sh
chmod +x ./cryptography/gpg/gpg_decryption.sh
chmod +x ./cryptography/openssl/openssl_encryption.sh
chmod +x ./cryptography/openssl/openssl_decryption.sh
chmod +x ./cryptography/zip/zip_encryption.sh
chmod +x ./cryptography/zip/zip_decryption.sh
chmod +x ./misc/exists.sh
chmod +x ./monitoring/cpu_monitoring.sh
chmod +x ./monitoring/mem_monitoring.sh

chmod +x ./cryptography/pyca/encrypt.py
chmod +x ./cryptography/pyca/decrypt.py
chmod +x ./monitoring/website_monitoring.py
chmod +x ./networking/ip_pinging.py
chmod +x ./networking/server_pinging.py

clear

echo -e "${g}Thanks for using Tilux!${w}"
echo

read -p "Do you want to run the script right now? (Y/n): " input
input="$(echo ${input} | tr 'A-Z' 'a-z')"
if [[ $input == "y" ]]; then
  clear
  ./tilux
else
  echo Exiting...
  sleep 1
  clear
  exit
fi
