#!/bin/bash

source ansi-colors

chmod +x tilux
chmod +x ./info/host.sh
chmod +x ./info/ip_addr.sh
chmod +x ./misc/exists.sh
chmod +x ./monitoring/cpu_monitoring.sh
chmod +x ./monitoring/mem_monitoring.sh

chmod +x ./misc/ip_pinging.py
chmod +x ./misc/server_pinging.py

clear

echo -e "${g}Thanks for using Tilux!${w}"
echo

read -p "Do you want to run the script right now? (Y/n): " input
input="$(echo ${input} | tr 'A-Z' 'a-z')"
if [[ $input == "y" ]]; then
  clear
  ./tilux
else
  echo Exiting...
  sleep 1
  clear
  exit
fi
