#!/bin/bash

# Seems redundant to add an util for bashpal suggestion
# but I want to keep at least some support for alias and PATH
# creation even if bashpal isn't installed.

# Hence why I'm only reusing a small part of the original code.
bashpal_suggestion() {
  echo "Doesn't check for duplicates nor creates the file ~/.bash_aliases."
  echo "I suggest installing bashpal."
  echo -e "\nsudo add-apt-repository ppa:endormi/ppapp && sudo apt update && sudo apt install bashpal\n"

  read -p "Do you want to continue? (Y/n) " continue
  continue="$(echo ${continue} | tr 'A-Z' 'a-z')"

  [ "$continue" != "y" ] && [ "$continue" != "yes" ] && echo "Exiting..." && exit
}
