#!/bin/bash

# Check if the package is installed
if ! command -v "$1" &>/dev/null; then
  echo "Installing $1 which is required to run this script."
  sudo apt update
  sudo apt install "$1"
  clear
fi
