#!/bin/bash

[ ! -d scripts ] && cd ..

# Creates a new file
[ ! -f ~/.bash_aliases ] && touch ~/.bash_aliases

. ~/.bash_aliases

alias="tvenv"

if alias "$alias" &>/dev/null; then
  echo "Alias $alias already exists!"
  exit
fi

echo "alias $alias='. $PWD/venv/bin/activate'" >> ~/.bash_aliases
echo "Added ${alias} to .bash_aliases"
exec "$BASH"
