#!/bin/bash

[ ! -d scripts ] && cd ..

# Creates a new file
[ ! -f ~/.bash_aliases ] && touch ~/.bash_aliases

. ~/.bash_aliases

alias="tilux"

[ `alias | grep "$alias" | wc -l` != 0 ] && echo "Alias $alias already exists" && exit

echo -e "\n# Running the tilux CLI\n# In order for the script to work, you need to cd in the folder\nalias $alias='cd $PWD && ./tilux'" >> ~/.bash_aliases
echo "Added ${alias} to .bash_aliases"
exec "$BASH"
