#!/bin/bash

[ ! -d scripts ] && cd ..

source scripts/utils/bashpal_suggestion

alias_name="tvenv"
cmd=". $PWD/venv/bin/activate"

if ! command -v bashpal &>/dev/null; then
  bashpal_suggestion
  bash_aliases_file=~/.bash_aliases
  echo "alias $alias_name='$cmd'" >> $bash_aliases_file
  echo -e "Added ${alias_name} to ${bash_aliases_file}"
else
  bashpal -a $alias_name -c "$cmd"
fi
