#!/bin/bash

[ ! -d scripts ] && cd ..

source scripts/utils/bash_aliases

alias_name="tvenv"
check_alias_exists $alias_name

echo "alias $alias_name='. $PWD/venv/bin/activate'" >> $bash_aliases_file
echo -e "Added ${alias_name} to ${bash_aliases_file}"

prompt_for_new_shell_session
