#!/bin/bash

[ ! -d scripts ] && cd ..

source scripts/utils/bash_aliases

directory=$PWD

if grep -Fxq "export PATH=\$PATH:$directory" $bash_aliases_file || alias $directory &>/dev/null; then
  echo "Directory or alias already exists in PATH!"
  exit
fi

echo "export PATH=\$PATH:$directory" >> $bash_aliases_file
echo "Added ${directory} PATH to ${bash_aliases_file}"

prompt_for_new_shell_session
