#!/bin/bash

[ ! -d scripts ] && cd ..

source scripts/utils/bash_aliases

alias_name="tilux"
check_alias_exists $alias_name

echo "alias $alias_name='cd $PWD && ./$alias_name'" >> $bash_aliases_file
echo -e "Added ${alias_name} to ${bash_aliases_file}"

prompt_for_new_shell_session
