#!/bin/bash

# TODO: Make better
[ ! -d scripts ] && cd ..
[ -d docs ] && cd docs

function cmd_install(){
  args="$1"
  cmd=$(pip3 show $args)

  if [ $? == 1 ]; then
    pip3 install $args
    clear
  fi
}

cmd_install sphinx
cmd_install myst-parser

make html
