#!/bin/bash

# TODO: Make better
[ ! -d scripts ] && cd ..
[ -d docs ] && cd docs

function cmd_install(){
  args="$1"
  if ! pip3 show $args >/dev/null 2>&1; then
    pip3 install $args
    clear
  fi
}

cmd_install sphinx
cmd_install myst-parser

make html
