#!/bin/bash

# TODO: Make better
[ ! -d scripts ] && cd ..
[ -d docs ] && cd docs

function cmd_install(){
  args="$1"
  cmd=$(pip3 show $args)

  [ "$?" == 1 ] && pip3 install $args && clear
}

cmd_install sphinx
cmd_install myst-parser

make html
