#!/bin/bash

[ ! -d scripts ] && cd ..

if [[ "$(which clang-format)" == "" ]]; then
  sudo apt update
  sudo apt install clang-format
  clear
fi

clang-format -i sys/file_folder/fs.c
clang-format -i sys/info/space.c
clang-format -i sys/proc/one_core.c
