#!/bin/bash

[ ! -d scripts ] && cd ..

if [[ "$(which clang-format)" == "" ]]; then
  sudo apt update
  sudo apt install clang-format
  clear
fi

clang-format -i proc.cpp
clang-format -i sys/fs.c
clang-format -i sys/space.c
