#!/bin/bash

# TODO: Make better
[ ! -d scripts ] && cd ..
[ ! -d docs ] && cd ..

./scripts/utils/check_and_install_package sed

docs_dir="docs/source"

copy_pairs() {
  cp "$1" "$docs_dir/$2"
}

file_pairs=(
  "GUIDE.md guide.md"
  "PACKAGES.md packages.md"
)

for pair in "${file_pairs[@]}"; do
  copy_pairs $pair
done

sed -i '2,7d' "$docs_dir/guide.md"
sed -i '30,31d' "$docs_dir/packages.md"
