#!/bin/bash

# TODO: Make better
[ ! -d scripts ] && cd ..
[ ! -d docs ] && cd ..

if [[ "$(which sed)" == "" ]]; then
  echo "Installing sed which is required to run this script."
  sudo apt update
  sudo apt install sed
  clear
fi

file_to_copy="docs/source/commands.md"
file_to_write="GUIDE.md"
new_text="# Guide"

cp $file_to_copy $file_to_write
sed -i "1 s/.*/$new_text/" $file_to_write
