#!/bin/bash

[ ! -d scripts ] && cd ..

if ! command -v groff &>/dev/null; then
  echo "Installing groff which is required to run this script."
  sudo apt update
  sudo apt install groff
  clear
fi

groff -man -Tascii ./man/tilux.1 | less
