#!/bin/bash

[ ! -d scripts ] && cd ..

# Works only with gnome terminal and xterm for now
resize_terminal() {
  terminal_cmd=$1
  geometry=$2
  echo "Resizing terminal.. (this will open a new terminal)"
  sleep 0.5
  $terminal_cmd $geometry 80x24
  echo "Done!"
  exit
}

if cat /etc/alternatives/x-terminal-emulator | grep exec | grep -q gnome; then
  resize_terminal gnome-terminal --geometry
elif cat /etc/alternatives/x-terminal-emulator | grep exec | grep -q xterm; then
  resize_terminal xterm -geometry
fi

echo "Terminal not recognized."
