#!/bin/bash

: '
  ------
  Quick hack to check if script is ran inside
  scripts folder and if it is CD out of the folder.

  resize_term script is meant to be ran inside tilux folder, not outside
  so this should not cause any errors.

  I did not create and include a function, because in order to
  source the file, same check would have been needed.
  ------
'

if [[ ! -d scripts ]]; then
  cd ..
fi

# Works only with gnome terminal and xterm for now
cmd_gnome=$(cat /etc/alternatives/x-terminal-emulator | grep exec | grep gnome)
cmd_xterm=$(cat /etc/alternatives/x-terminal-emulator | grep exec | grep xterm)

[ $cmd_gnome != 0 ] && echo -e "\nResizing terminal.. (this will open a new terminal)" && sleep .5 && gnome-terminal --geometry 85x25 && echo -e "Done!\n" && exit
[ $cmd_xterm != 0 ] && echo -e "\nResizing terminal.. (this will open a new terminal)" && sleep .5 && xterm -geometry 85x25 && echo -e "Done!\n" && exit

echo "Terminal not recognized."
