#!/bin/bash

[ ! -d scripts ] && cd ..

if [[ "$(which flake8)" == "" ]]; then
  sudo apt update
  sudo apt install flake8
  clear
fi

# Run flake8 with settings configured in .flake8
echo "flake8 might take a while..."
flake8
