#!/bin/bash

[ ! -d scripts ] && cd ..

if [[ "$(which flake8)" == "" ]]; then
  echo "Installing flake8 which is required to run this script."
  sudo apt update
  sudo apt install flake8
  clear
fi

# Run flake8 with settings configured in .flake8
flake8 . --show-source --statistics
