#!/bin/bash

[ ! -d scripts ] && cd ..

# Run Makefile
make

if [[ "$(which flake8)" == "" ]]; then
  sudo apt update
  sudo apt install flake8
  clear
fi

# Run flake8 with settings configured in .flake8
flake8

[ "$(which rubocop)" == "" ] && gem install rubocop -v '~> 1.9.1'

# Run rubocop with settings configured in .rubocop.yml
rubocop
