#!/bin/bash

[ ! -d scripts ] && cd ..

if ! command -v docker &>/dev/null || ! command -v docker-compose &>/dev/null; then
  echo "Installing docker and docker-compose which are required to run this script."
  sudo apt update
  sudo apt install docker.io docker-compose
  clear
fi

docker-compose build
docker-compose up -d
