#!/bin/bash

if [[ ! -d scripts ]]; then
  cd ..
fi

if [[ "$(which docker)" == "" || "$(which docker-compose)" == "" ]]; then
  echo "You need to install Docker && Docker-Compose"
  exit
fi

docker-compose build
docker-compose up -d
