#!/bin/bash

# TODO:
# Fix: some ansi-colors don't work in the ruby version

# I used a function since i'm using the same text multiple times
til () {
  echo -e "  {1} -- Host (name, OS, kernel version & more)"
  echo "  {2} -- 5 choices for encryption and decryption"
  echo "  {3} -- Monitoring different processes"
  echo "  {4} -- Pinging networks"
  echo "  {5} -- System scripts"
  echo -e "  {--help} -- How to use Tilux?\n"
}


help () {
 echo Interactive:
 echo -e "Running the files interactively ./tilux and then follow the choices\n"
 echo Args:
 echo "Running the files with args ./tilux (and then the argument e.g. cryptography -c -e)"
 echo -e "Note: The uppercase doesn't work currently with args\n"

 echo "info: host (name, OS, kernel version, DNS domain and local IP address)"
 echo "cryptography -c: ccrypt -e (for encryption) or -d (for decryption)"
 echo "cryptography -g: GPG -e (for encryption) or -d (for decryption)"
 echo "cryptography -o: Openssl -e (for encryption) or -d (for decryption)"
 echo "cryptography -p: Pyca -e (for encryption) or -d (for decryption)"
 echo "cryptography -z: Zip -e (for encryption) or -d (for decryption)"
 echo "monitoring -c: monitoring cpu processes"
 echo "monitoring -m: monitoring memory consumption"
 echo "monitoring -w: monitoring website (if it's up and if not it sends an email)"
 echo "networking -i: IP pinging"
 echo "networking -s: Server pinging"
 echo "system -b: bf (backup folder)"
 echo "system -c: clean (clean system of logs and trash)"
 echo "system -d: del (Delete file or directory)"
 echo "system -e: exists (Check if file or dir exists)"
 echo "system -f: fd (number of files and folders)"
 echo "system -fl: file updated"
 echo "system -fs: file size"
 echo "system -l: last updated (file)"
 echo "system -p: parse date"
 echo "system -r: root (check if you are root or not)"
 echo -n "Press [ENTER] to continue..."
 read
}
help2 () {
  echo -e "How to use Tilux?\n"
}
info () {
 echo -e "Host (name, OS, kernel version & more)\n"
}
cryptography () {
 echo "cryptography -c: ccrypt"
 echo "cryptography -g: GPG"
 echo "cryptography -o: Openssl"
 echo "cryptography -p: Pyca"
 echo -e "cryptography -z: Zip\n"
}
monitoring () {
 echo "-c: cpu_monitoring"
 echo "-m: mem_monitoring"
 echo -e "-w: website_monitoring\n"
}
networking () {
 echo "-i: ip_pinging"
 echo -e "-s: server_pinging\n"
}
sys () {
 echo "-b: bf (backup folder)"
 echo "-c: clean (clean system of logs and trash)"
 echo "-d: del (delete file or directory)"
 echo "-e: exists (file or directory)"
 echo "-f: fd (number of files and folders"
 echo "-fl: file updated"
 echo "-fs: file size"
 echo "-l: last updated (file)"
 echo "-p: parse date"
 echo -e "-r: root (check if you are root or not)\n"
}
# misc () {}


# Required for running in tilux.rb
if [[ $1 == "help" ]]; then
  help
elif [[ $1 == "info" ]]; then
  info
elif [[ $1 == "cryptography" ]]; then
  cryptography
elif [[ $1 == "monitoring" ]]; then
  monitoring
elif [[ $1 == "networking" ]]; then
  networking
elif [[ $1 == "sys" ]]; then
  sys
elif [[ $1 == "misc" ]]; then
  misc
elif [[ $1 == "help2" ]]; then
  help2
elif [[ $1 == "til" ]]; then
  til
fi
