#!/bin/bash

check_and_install_package() {
  package=$1

  if ! command -v "$package" &>/dev/null; then
    echo "Installing $package which is required to run this script."
    sudo apt update
    sudo apt install $package
    clear
  fi
}

check_and_install_package jq
check_and_install_package unzip

latest_version=$(curl -sL https://api.github.com/repos/endormi/tilux/releases/latest | jq -r ".tag_name")
file_ext="zip"
wget https://github.com/endormi/tilux/archive/refs/tags/$latest_version.$file_ext && unzip $latest_version.$file_ext && rm $latest_version.$file_ext
