#!/bin/bash

command -v ruby &>/dev/null || echo "NOTE: Certain scripts require ruby."

sleep 1

# Scripts I find to be the most useful
url="https://raw.githubusercontent.com/endormi/tilux/master"
scripts=(
  "sys/file_folder/clean.sh"
  "sys/file_folder/file_updated.rb"
  "sys/file_folder/last_updated.sh"
  "sys/info/bit.sh"
  "sys/info/ip.rb"
  "sys/info/root.rb"
  "sys/other/parse_date.rb"
)

for script in "${scripts[@]}"
do
  wget $url/$script
done
