name: docker-compose-action-CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Up
        run: docker-compose up -d
      - name: Down
        run: docker-compose down
