name: flake8
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-flake8
        run: sudo apt install flake8
      - name: flake8
        run: flake8
