name: make

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'sys/**/**.c'
      - 'sys/**/**.h'
      - 'tools/**.h'
  pull_request:
    paths:
      - 'docs/**'
      - 'sys/**/**.c'
      - 'sys/**/**.h'
      - 'tools/**.h'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Run docs
        run: make docs
      - name: Clean files
        run: make clean
