name: make

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run make
        run: make
      - run: sudo apt install clang-format-10
      - name: Run clang-format check
        run: make cformat_check
      - name: Clean files
        run: make clean
