name: rubocop
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rubocop
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        with:
          action_config_path: ".rubocop.yml"
