name: rubocop
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true
    - run: gem install rubocop -v '~> 1.9.1'
    - run: rubocop
