name: ruby

on:
  push:
    branches:
      - master
    paths:
      - '**.rb'
      - '**/**.rb'
      - '**/**/**.rb'
  pull_request:
    paths:
      - '**.rb'
      - '**/**.rb'
      - '**/**/**.rb'

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install rspec
      run: gem install rspec -v 3.12.0
    - name: Run rspec tests
      run: rake
    - name: Install rubocop
      run: gem install rubocop -v '~> 1.9.1'
    - name: Check Rubocop
      run: rubocop

    - name: Install Code Scanning integration
      run: bundle add code-scanning-rubocop --skip-install

    - name: Install dependencies
      run: bundle install

    - name: Run code scan
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "
    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rubocop.sarif
