name: Update Year

on:
  schedule:
    - cron: "0 1 1 1 *" # 01:00 on January 1

jobs:
  update_year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update year in specified files
        uses: endormi/yearplusplus@v2
        with:
          files: 'LICENSE docs/source/conf.py'
          username: 'Year++'
          email: '<>'
