name: Update year

on:
  pull_request:
#  schedule:
#    - cron: "0 1 1 1 *" # 01:00 on January 1

jobs:
  year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Update docs year
        run: |          
          last_year=$(date --date="1 year ago" +%Y)
          current_year=$(date +%Y)

          find docs/source/conf.py -exec sed -i "s/${current_year}/${last_year}/g" {} \;
      
      - name: Update license year
      - uses: FantasticFiasco/action-update-license-year@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
